### ISSUE TITLE
[job mkdir] Job error: Error collecting output for parameter 'blastdb': wf_makeblastdb.cwl:76:13: Did not find output file with glob pattern: '['AMRProt']'

### ISSUE THREAD

**Issue by clinardi** [ncbi/pipelines#5]
Dear NCBI Team,

I am trying to run AMRFinder in a docker image. I have installed all the dependencies required but when testing it, the following error occurs.

(cwl) root@4003:/l3bioinfo/amr_finder# ./amrfinder -n test_dna.fa -s
Required supplementary data not present, downloading via ftp.
  Fetching AMR.LIB...success!
  Fetching AMRProt...success!
  Fetching AMR_CDS...success!
  Fetching fam.tab...success!
  Fetching changes.txt...success!
/l3bioinfo/cwl/bin/cwl-runner 1.0.20181118133959
Resolved '/l3bioinfo/amr_finder/wf_amr_dna.cwl' to 'file:///l3bioinfo/amr_finder/wf_amr_dna.cwl'
[workflow ] start
[workflow ] starting step fasta_check
[step fasta_check] start
[job fasta_check] /tmp/tmprYJ1tL$ docker \
    run \
    -i \
    --volume=/tmp/tmprYJ1tL:/jgWagD:rw \
    --volume=/tmp/tmpwCW7AA:/tmp:rw \
    --volume=/l3bioinfo/amr_finder/test_dna.fa:/var/lib/cwl/stgc822ef1a-9c28-490a-953c-dd8bd4aa8ee2/test_dna.fa:ro \
    --workdir=/jgWagD \
    --read-only=true \
    --log-driver=none \
    --user=0:0 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/jgWagD \
    ncbi/amr:18.06 \
    fasta_check \
    /var/lib/cwl/stgc822ef1a-9c28-490a-953c-dd8bd4aa8ee2/test_dna.fa > /tmp/tmprYJ1tL/fasta_check.out
[job fasta_check] completed permanentFail
[step fasta_check] completed permanentFail
[workflow ] completed permanentFail
{
    "fasta_check_out": {
        "checksum": "sha1$ba94ee660aac5c886bfd4dff8db76dc196687907",
        "basename": "fasta_check.out",
        "location": "file:///l3bioinfo/amr_finder/fasta_check.out",
        "path": "/l3bioinfo/amr_finder/fasta_check.out",
        "class": "File",
        "size": 213
    },
    "result": null
}
Final process status is permanentFail

ERROR
Reading line 0:

"common.cpp", line 645: i >= 0 && i <= 255
HOSTNAME: adadbe9f05a0
PWD: ?
Progam name: fasta_check
Command line: fasta_check /var/lib/cwl/stgc822ef1a-9c28-490a-953c-dd8bd4aa8ee2/test_dna.fa

What might be causing this problem?

I think it might have something to do with docker. The command I used to have docker inside the container is

cl@b:~$ docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v/usr/bin/docker:/usr/bin/docker amr-image:v2 bash

Thank you for your time and I look forward to your reply!

**Comment by slottad** [comment]
You are trying to run docker within docker? I'm sorry, we have never tested that configuration. 

Due to many user requests, and troubles we have had with docker, we are trying a new route for distribution. Please check out our new version here:  https://github.com/ncbi/amr/wiki/Installing-AMRFinder

Note that this is just ncbi/amr and not ncbi/pipelines/amr. We have moved this to a dedicated repository. This is still in progress, so please bear with us.

**Comment by clinardi** [comment]
Thank you very much for your reply and help! It works perfectly now. I am extremely grateful for your help and assistance. Thank you once again
